# fly.toml file generated for obits on 2023-03-06T16:24:00-06:00

app = "numnum"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

# [mounts]
#   source="numnum_storage"
#   destination="/app/storage"

[[statics]]
  guest_path = "/app/frontend-dist/assets"
  url_prefix = "/assets"


[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[deploy]
  release_command = "python manage.py migrate --fake-initial --noinput"

[experimental]
  auto_rollback = true
