name: Django Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # pg healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DB_HOST: '127.0.0.1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: sudo apt-get install -y postgresql-client
      - run: pip3 install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: python manage.py migrate
      - run: python -m pytest
